const { app, BrowserWindow, dialog, ipcMain } = require('electron'); const path = require('path'); const fs = require('fs/promises'); const { execFile } = require('child_process'); const { promisify } = require('util'); const { randomUUID } = require('crypto'); const chokidar = require('chokidar'); const pty = require('node-pty'); const execFileAsync = promisify(execFile)
let win, root, watcher; const terminals = new Map(); const recentKey = 'recent-workspaces.json'
const stateFile = () => path.join(app.getPath('userData'), recentKey)
const safe = relative => { if (!root) throw new Error('Open a workspace first'); const target = path.resolve(root, relative || '.'); if (target !== root && !target.startsWith(root + path.sep)) throw new Error('Invalid workspace path'); return target }
const tree = async dir => { const items = await fs.readdir(dir, { withFileTypes:true }); return Promise.all(items.filter(item => item.name !== '.git').sort((a,b) => Number(b.isDirectory()) - Number(a.isDirectory()) || a.name.localeCompare(b.name)).map(async item => { const full = path.join(dir, item.name); const relative = path.relative(root, full); return item.isDirectory() ? { kind:'directory', name:item.name, path:relative, children:await tree(full) } : { kind:'file', name:item.name, path:relative } })) }
const remember = async () => { let items = []; try { items = JSON.parse(await fs.readFile(stateFile(), 'utf8')) } catch {} items = items.filter(item => item.path !== root); items.unshift({ path:root, name:path.basename(root), openedAt:Date.now() }); await fs.writeFile(stateFile(), JSON.stringify(items.slice(0,12))) }
const watch = () => { watcher?.close(); watcher = chokidar.watch(root, { ignoreInitial:true, ignored:/[\\/]node_modules[\\/]/ }); watcher.on('all', (event, file) => win?.webContents.send('workspace:changed', { event, path:path.relative(root, file) })) }
const open = async () => { const result = await dialog.showOpenDialog(win, { properties:['openDirectory'] }); if (result.canceled) return null; root = path.resolve(result.filePaths[0]); await remember(); watch(); return { name:path.basename(root), path:root, tree:await tree(root) } }
const shell = () => process.platform === 'win32' ? 'powershell.exe' : process.env.SHELL || '/bin/bash'
ipcMain.handle('workspace:open', open); ipcMain.handle('workspace:tree', async () => root ? { name:path.basename(root), path:root, tree:await tree(root) } : null); ipcMain.handle('workspace:read', (_e, p) => fs.readFile(safe(p), 'utf8')); ipcMain.handle('workspace:write', (_e,p,data) => fs.writeFile(safe(p), data, 'utf8')); ipcMain.handle('workspace:createFile', (_e,p,data) => fs.writeFile(safe(p), data, { encoding:'utf8', flag:'wx' })); ipcMain.handle('workspace:createFolder', (_e,p) => fs.mkdir(safe(p), { recursive:false })); ipcMain.handle('workspace:rename', (_e,from,to) => fs.rename(safe(from), safe(to))); ipcMain.handle('workspace:move', (_e,from,to) => fs.rename(safe(from), safe(to))); ipcMain.handle('workspace:remove', async (_e,p) => { const result = await dialog.showMessageBox(win, { type:'warning', buttons:['Delete','Cancel'], defaultId:1, message:`Delete ${path.basename(p)}?`, detail:'This permanently removes it from the selected workspace.' }); if (result.response === 0) await fs.rm(safe(p), { recursive:true, force:false }) }); ipcMain.handle('workspace:recent', async () => { try{return JSON.parse(await fs.readFile(stateFile(),'utf8'))}catch{return[]} });
const inWorkspace = target => target === root || target.startsWith(root + path.sep)
const terminalError = message => ({ ok:false, output:`ERROR: ${message}` })
ipcMain.handle('terminal:create', () => { if (!root) return terminalError('Open a workspace before starting a terminal.'); const id = randomUUID(); const proc = pty.spawn(shell(), [], { cwd:root, name:'xterm-color', cols:100, rows:24, env:process.env }); const session = { sessionId:id, workspacePath:root, currentWorkingDirectory:root, shell:shell(), processId:proc.pid, process:proc }; terminals.set(id, session); proc.onData(data => win?.webContents.send('terminal:data',{id,data})); proc.onExit(() => terminals.delete(id)); console.info('terminal session created', { id, workspacePath:root, cwd:root, pid:proc.pid }); return { ok:true, ...session, process:undefined } });
ipcMain.handle('terminal:execute', async (_event, id, command) => { const session = terminals.get(id); if (!session) return terminalError('Terminal session is unavailable. Open a workspace and retry.'); const input = String(command || '').trim(); if (!input) return { ok:true, cwd:session.currentWorkingDirectory, output:'' }; console.info('terminal command', { sessionId:id, workspacePath:session.workspacePath, cwd:session.currentWorkingDirectory, command:input }); try { const [verb, ...parts] = input.split(/\s+/); if (verb.toLowerCase() === 'clear' || verb.toLowerCase() === 'cls') return { ok:true, clear:true, cwd:session.currentWorkingDirectory, output:'' }; if (verb.toLowerCase() === 'pwd') return { ok:true, cwd:session.currentWorkingDirectory, output:session.currentWorkingDirectory }; if (verb.toLowerCase() === 'cd') { const requested = parts.join(' ') || session.workspacePath; const target = path.resolve(session.currentWorkingDirectory, requested); console.info('terminal cd resolve', { requested, resolved:target }); if (!inWorkspace(target)) return terminalError('Directory is outside the opened workspace.'); const stat = await fs.stat(target).catch(() => null); if (!stat?.isDirectory()) return terminalError(`Directory "${requested}" not found.`); session.currentWorkingDirectory = target; return { ok:true, cwd:target, output:'' } } if (verb.toLowerCase() === 'dir' || verb.toLowerCase() === 'ls') { const entries = await fs.readdir(session.currentWorkingDirectory, { withFileTypes:true }); return { ok:true, cwd:session.currentWorkingDirectory, output:entries.map(item => `${item.isDirectory() ? '[DIR] ' : '      '}${item.name}`).join('\n') } } const commandArgs = process.platform === 'win32' ? ['-NoProfile','-Command',input] : ['-lc',input]; const result = await execFileAsync(session.shell, commandArgs, { cwd:session.currentWorkingDirectory, timeout:120000, windowsHide:true }); const output = [result.stdout, result.stderr].filter(Boolean).join('\n'); console.info('terminal result', { sessionId:id, cwd:session.currentWorkingDirectory, output }); return { ok:true, cwd:session.currentWorkingDirectory, output } } catch (error) { console.error('terminal execution error', { sessionId:id, cwd:session.currentWorkingDirectory, message:error.message }); return terminalError(error.stderr || error.message || 'Command failed.') } });
ipcMain.on('terminal:write', (_e,id,input) => terminals.get(id)?.process?.write(input)); ipcMain.on('terminal:resize', (_e,id,cols,rows) => terminals.get(id)?.process?.resize(cols,rows)); ipcMain.on('terminal:close', (_e,id) => terminals.get(id)?.process?.kill());
const createWindow = () => { win = new BrowserWindow({ width:1440, height:900, minWidth:960, minHeight:640, webPreferences:{ contextIsolation:true, nodeIntegration:false, preload:path.join(__dirname,'preload.cjs') } }); const devUrl = process.env.VITE_DEV_SERVER_URL; if (devUrl) win.loadURL(devUrl); else win.loadFile(path.join(__dirname, '..', 'dist', 'index.html')) }; app.whenReady().then(createWindow); app.on('window-all-closed', () => { watcher?.close(); if(process.platform !== 'darwin') app.quit() })
