const desktop = () => window.tokenpilotDesktop?.workspace
const DB = 'tokenpilot-workspaces'; const STORE = 'handles'
const db = () => new Promise((resolve, reject) => { const request = indexedDB.open(DB, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) })
const put = async (key, value) => { const database = await db(); return new Promise((resolve, reject) => { const tx = database.transaction(STORE, 'readwrite'); tx.objectStore(STORE).put(value, key); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error) }) }
const get = async key => { const database = await db(); return new Promise((resolve, reject) => { const request = database.transaction(STORE).objectStore(STORE).get(key); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) }) }
const join = (parent, name) => parent ? `${parent}/${name}` : name
const childrenOf = result => Array.isArray(result) ? result : result?.children || []
const scanFile = async (handle,path) => { const file = await handle.getFile(); return { kind:'file',name:handle.name,path,handle,size:file.size,modified:file.lastModified } }
const scanFolder = async (handle,path='') => { const children=[]; for await(const child of handle.values()) children.push(child.kind === 'directory' ? await scanFolder(child,join(path,child.name)) : await scanFile(child,join(path,child.name))); return {kind:'directory',name:handle.name,path,handle,children:children.sort((a,b)=>a.kind===b.kind?a.name.localeCompare(b.name):a.kind==='directory'?-1:1)} }
class WorkspaceManager { constructor(){this.root=null;this.tree=null;this.recentKey='tokenpilot-recent-workspaces'} get native(){return !!desktop()} get supported(){return this.native || 'showDirectoryPicker' in window} async open(){if(this.native){const workspace=await desktop().open();if(workspace){this.root=workspace;this.tree=workspace.tree}return this.tree}if(!this.supported)throw new Error('Use the TokenPilot desktop app or Chrome/Edge to open a local folder.');const handle=await window.showDirectoryPicker({mode:'readwrite'});return this.setRoot(handle)} async setRoot(handle){const permission=await handle.requestPermission({mode:'readwrite'});if(permission!=='granted')throw new Error('Folder write permission was not granted.');this.root=handle;await put('last',handle);this.tree=await scanFolder(handle);return this.tree} async restore(){if(this.native)return null;const handle=await get('last');if(!handle||await handle.queryPermission({mode:'readwrite'})!=='granted')return null;this.root=handle;this.tree=await scanFolder(handle);return this.tree} async refresh(){if(this.native){const workspace=await desktop().tree();this.root=workspace;this.tree=workspace?.tree;return this.tree}if(!this.root)return null;this.tree=await scanFolder(this.root);return this.tree} async read(node){return this.native?desktop().read(node.path):(await node.handle.getFile()).text()} async context(max=120000){const result=await this.refresh();const nodes=[];const visit=async items=>{for(const item of items||[]){if(item.kind==='directory'){nodes.push(`[folder] ${item.path}`);await visit(item.children)}else{let line=`[file] ${item.path}`;if(/\.(html?|css|js|jsx|ts|tsx|json|md|py|sql)$/i.test(item.name)){try{const text=await this.read(item);line+=`\n${text.slice(0,8000)}`}catch{}}nodes.push(line)}}};await visit(childrenOf(result));return nodes.join('\n').slice(0,max)} async write(node,content){if(this.native){await desktop().write(node.path,content);return this.refresh()}const writable=await node.handle.createWritable();await writable.write(content);await writable.close();return this.refresh()} async createFile(parent,name,content=''){if(this.native){await desktop().createFile(join(parent.path,name),content);return this.refresh()}const handle=await parent.handle.getFileHandle(name,{create:true});const writable=await handle.createWritable();await writable.write(content);await writable.close();return this.refresh()} async createFolder(parent,name){if(this.native){await desktop().createFolder(join(parent.path,name));return this.refresh()}await parent.handle.getDirectoryHandle(name,{create:true});return this.refresh()} async remove(node){if(this.native){await desktop().remove(node.path);return this.refresh()}await node.handle.remove({recursive:node.kind==='directory'});return this.refresh()} onChanged(callback){return this.native?desktop().onChanged(callback):()=>{}} }
WorkspaceManager.prototype.close = async function() { this.root = null; this.tree = null; window.tokenpilotWorkspaceContext = ''; return true }
export const workspaceManager = new WorkspaceManager()
