"""add_profile_security_bug_report_tables

Revision ID: 65c05bb1ffa1
Revises: c9e8d7f6a5b4
Create Date: 2026-07-18 19:51:23.296658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c05bb1ffa1'
down_revision: Union[str, Sequence[str], None] = 'c9e8d7f6a5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_name', sa.String(length=255), nullable=False),
    sa.Column('reporter_email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_reports_id'), 'bug_reports', ['id'], unique=False)
    op.create_table('security_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_logs_id'), 'security_logs', ['id'], unique=False)
    op.create_index(op.f('ix_security_logs_user_id'), 'security_logs', ['user_id'], unique=False)
    op.add_column('companies', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employees', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('designation', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'designation')
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'avatar_url')
    op.drop_column('employees', 'postal_code')
    op.drop_column('employees', 'country')
    op.drop_column('employees', 'state')
    op.drop_column('employees', 'city')
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'phone')
    op.drop_column('employees', 'last_login_at')
    op.drop_column('companies', 'company_size')
    op.drop_column('companies', 'industry')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'avatar_url')
    op.drop_column('companies', 'postal_code')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'last_login_at')
    op.drop_index(op.f('ix_security_logs_user_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_id'), table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_index(op.f('ix_bug_reports_id'), table_name='bug_reports')
    op.drop_table('bug_reports')
    # ### end Alembic commands ###
