import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRight, BarChart3, Building2, DollarSign, Layers3, LockKeyhole, ShieldCheck, Sparkles, Zap } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import Logo from '../components/Logo'
import AINetworkBackground from '../components/AINetworkBackground'
import '../benefits.css'

export default function Landing() {
  return <div className="landing landing-reference">
    <header className="landing-nav"><Logo/><nav><a href="#product">Product</a><a href="#benefits">Benefits</a><a href="#faq">FAQ</a></nav><div className="landing-nav-actions"><Link className="button ghost" to="/login">Sign in</Link></div></header>
    <section className="hero"><AINetworkBackground/><div className="eyebrow"><Sparkles size={17}/> The calm command center for AI usage</div><motion.h1 className="hero-quote" initial="hidden" animate="visible"><span className="hero-quote-line">{['Every', 'Token', 'Counts.'].map((word, index) => <motion.span key={word} variants={quoteWordVariants} custom={index} className="hero-word">{word}</motion.span>)}</span><span className="gradient-text hero-quote-line">{['Make', 'Yours', 'Smarter.'].map((word, index) => <motion.span key={word} variants={quoteWordVariants} custom={index + 3} className="hero-word">{word}</motion.span>)}</span></motion.h1><p className="hero-copy">Optimize prompts, reduce context, eliminate redundant requests, and lower AI costs without sacrificing response quality.</p><div className="hero-actions"><Link className="button primary large" to="/register">Build your workspace <ArrowRight size={21}/></Link><a className="button secondary large" href="#product">Explore platform</a></div></section>
    <section className="trust"><span>AI Token Reduction</span><b>AI Governance</b><b>Token Budgets</b><b>Usage Analytics</b><b>Team Access</b></section>
    <section id="product" className="section"><div className="section-label">The platform</div><h2>One clear view of your<br/><span className="gradient-text">AI operating system.</span></h2><div className="feature-grid"><Feature Icon={BarChart3} title="Optimize Token Usage" text="Identify unnecessary token consumption, optimize prompts, and reduce AI costs with actionable insights across every team and model."/><Feature Icon={ShieldCheck} title="Set healthy boundaries" text="Assign budgets, control model access, and give every team the permissions they need."/><Feature Icon={Layers3} title="Scale without chaos" text="Build unlimited reporting hierarchies while keeping budgets, permissions, and visibility aligned."/></div></section>
    <BenefitsSection/><FaqSection/><footer><Logo/><span>© 2026 TokenPilot. Built for the next era of work.</span><Link to="/login">Open workspace →</Link></footer>
  </div>
}

function BenefitsSection() {
  const benefits = [[ShieldCheck, 'Token Optimization', 'Reduce unnecessary token consumption, optimize prompts, and lower AI costs with intelligent usage insights across every team and model.'], [DollarSign, 'Token Budget Management', 'Assign budgets to teams and monitor AI spending before costs become unpredictable.'], [BarChart3, 'Usage Analytics', 'Track token consumption, AI requests, and organization-wide usage from one dashboard.'], [Building2, 'Organization Hierarchy', 'Support unlimited reporting levels while keeping permissions and visibility aligned.'], [Zap, 'Team Productivity', 'Invite employees, assign responsibilities, and onboard new teams in minutes.'], [LockKeyhole, 'Enterprise Security', 'Secure authentication, JWT protection, invitation-based onboarding, and organization-level access control.']]
  return <section id="benefits" className="benefits-section"><div className="benefits-intro"><div className="section-label">Benefits</div><h2>Why organizations<br/><span className="gradient-text">choose TokenPilot.</span></h2><p>Everything organizations need to securely manage, govern, and optimize AI usage across teams from a single platform.</p></div><div className="benefits-grid">{benefits.map(([Icon, title, text], index) => <motion.div key={title} className="benefit-card" initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .45, delay: index * .06 }} whileHover={{ y: -5, scale: 1.02 }}><div className="benefit-icon"><Icon size={20}/></div><h3>{title}</h3><p>{text}</p></motion.div>)}</div></section>
}

function FaqSection() {
  const [expanded, setExpanded] = useState(false)
  const faqs = [['Who is TokenPilot built for?', 'TokenPilot is designed for organizations using AI across multiple teams. It helps companies manage access, monitor usage, assign token budgets, and maintain visibility as AI adoption grows.'], ['How does TokenPilot control AI usage?', 'Organizations can assign token budgets, manage role-based permissions, monitor AI usage, and control access to supported AI models from a centralized dashboard.'], ['How does TokenPilot optimize token usage?', 'TokenPilot analyzes AI requests to identify unnecessary token consumption, inefficient prompts, and usage patterns.'], ['Can TokenPilot scale with my organization?', 'Yes. TokenPilot supports multi-level organizational hierarchies while keeping visibility and governance aligned.'], ['How is access managed?', 'Access is controlled through secure authentication, invitation-based onboarding, and role-based permissions.']]
  return <section id="faq" className="section faq"><div><div className="section-label">Questions</div><h2>Simple by design.</h2></div><div>{faqs.slice(0, 3).map(([question, answer], index) => <FaqItem key={question} question={question} answer={answer} open={index === 0}/>)}<AnimatePresence initial={false}>{expanded && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} style={{ overflow: 'hidden' }}>{faqs.slice(3).map(([question, answer]) => <FaqItem key={question} question={question} answer={answer}/>)}</motion.div>}</AnimatePresence><div className="hero-actions"><button className="button secondary" onClick={() => setExpanded(value => !value)}>{expanded ? 'Show Less' : 'Show More Questions'}</button></div></div></section>
}

function FaqItem({ question, answer, open = false }) { return <details open={open}><summary>{question}</summary><p>{answer}</p></details> }
function Feature({ Icon, title, text }) { return <motion.div className="feature-card" whileHover={{ y: -6 }}><div className="feature-icon"><Icon size={21}/></div><h3>{title}</h3><p>{text}</p></motion.div> }

const quoteWordVariants = { hidden: { opacity: 0, y: 10 }, visible: index => ({ opacity: 1, y: 0, transition: { duration: .3, delay: index * .12, ease: [.22, 1, .36, 1] } }) }
