import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRight, BarChart3, Building2, DollarSign, Layers3, LockKeyhole, ShieldCheck, Sparkles, Zap } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import Logo from '../components/Logo'
import AINetworkBackground from '../components/AINetworkBackground'
import { useAuth } from '../contexts/AuthContext'
import '../benefits.css'

export default function Landing() {
  return <div className="landing"><header className="landing-nav"><Logo/><nav><a href="#product">Product</a><a href="#benefits">Benefits</a><a href="#faq">FAQ</a></nav><div className="landing-nav-actions"><Link className="button ghost" to="/login">Sign in</Link></div></header><section className="hero"><AINetworkBackground/><div className="eyebrow"><Sparkles size={14}/> The calm command center for AI usage</div><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}>Make every AI token<br/><span className="gradient-text">work harder.</span></motion.h1><p className="hero-copy">TokenPilot helps organizations manage budgets, monitor AI usage, govern access, and optimize costs across every team and model.</p><div className="hero-actions"><Link className="button primary large" to="/register">Build your workspace <ArrowRight size={17}/></Link><a className="button secondary large" href="#product">Explore platform</a></div><div className="hero-orb"><div className="orb-grid"/><div className="orb-card"><div className="mini-label">WORKSPACE VISIBILITY</div><strong>AI usage, budgets, access</strong><span className="positive">Across every team and model</span><div className="sparkline"/></div></div></section><section className="trust"><span>Built for thoughtful teams</span><b>AI governance</b><b>Token budgets</b><b>Usage analytics</b><b>Team access</b></section><section id="product" className="section"><div className="section-label">The platform</div><h2>One clear view of your<br/><span className="gradient-text">AI operating system.</span></h2><div className="feature-grid"><Feature Icon={BarChart3} title="See the signal" text="Turn raw AI usage into insights your entire organization can understand."/><Feature Icon={ShieldCheck} title="Set healthy boundaries" text="Assign budgets, control model access, and give every team the permissions they need."/><Feature Icon={Layers3} title="Scale without chaos" text="Build unlimited reporting hierarchies while keeping budgets, permissions, and visibility aligned."/></div></section><BenefitsSection/><FaqSection/><footer><Logo/><span>© 2026 TokenPilot. Built for the next era of work.</span><Link to="/login">Open workspace →</Link></footer></div>
}

function BenefitsSection() {
  const benefits = [[ShieldCheck, 'AI Governance', 'Control who can access AI models with enterprise-grade role-based permissions.'], [DollarSign, 'Token Budget Management', 'Assign budgets to teams and monitor AI spending before costs become unpredictable.'], [BarChart3, 'Usage Analytics', 'Track token consumption, AI requests, and organization-wide usage from one dashboard.'], [Building2, 'Organization Hierarchy', 'Support unlimited reporting levels while keeping permissions and visibility aligned.'], [Zap, 'Team Productivity', 'Invite employees, assign responsibilities, and onboard new teams in minutes.'], [LockKeyhole, 'Enterprise Security', 'Secure authentication, JWT protection, invitation-based onboarding, and organization-level access control.']]
  return <section id="benefits" className="benefits-section"><div className="benefits-intro"><div className="section-label">Benefits</div><h2>Why organizations<br/><span className="gradient-text">choose TokenPilot.</span></h2><p>Everything organizations need to securely manage, govern, and optimize AI usage across teams from a single platform.</p></div><div className="benefits-grid">{benefits.map(([Icon, title, text], index) => <motion.div key={title} className="benefit-card" initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.45,delay:index*.06}} whileHover={{y:-5,scale:1.02}}><div className="benefit-icon"><Icon size={20}/></div><h3>{title}</h3><p>{text}</p></motion.div>)}</div></section>
}

function FaqSection() {
  const [expanded, setExpanded] = useState(false)
  const faqs = [['Who is TokenPilot built for?', 'TokenPilot is designed for organizations using AI across multiple teams. It helps companies manage access, monitor usage, assign token budgets, and maintain visibility as AI adoption grows.'], ['How does TokenPilot control AI usage?', 'Organizations can assign token budgets, manage role-based permissions, monitor AI usage, and control access to supported AI models from a centralized dashboard.'], ['Can TokenPilot scale with my organization?', 'Yes. TokenPilot supports multi-level organizational hierarchies where companies, team leads, and employees can grow without losing visibility or governance.'], ['How is access managed?', 'Access is controlled through secure authentication, invitation-based onboarding, and role-based permissions. Employees only see the data and resources they are authorized to access.'], ['Is our data secure?', 'TokenPilot uses JWT authentication, role-based access control, and organization-level isolation to ensure users only access information they are permitted to view.'], ['Which AI models are supported?', 'TokenPilot is designed to work with multiple AI providers and is built to manage model access, usage tracking, and cost optimization across supported providers.'], ['Why use TokenPilot instead of direct AI APIs?', 'Instead of every employee using AI independently, TokenPilot gives organizations centralized governance, budgeting, analytics, and visibility over AI usage while reducing operational overhead.']]
  return <section id="faq" className="section faq"><div><div className="section-label">Questions</div><h2>Simple by design.</h2></div><div><FaqItem question={faqs[0][0]} answer={faqs[0][1]} open/><FaqItem question={faqs[1][0]} answer={faqs[1][1]}/><FaqItem question={faqs[2][0]} answer={faqs[2][1]}/><AnimatePresence initial={false}>{expanded && <motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:.35,ease:[.22,1,.36,1]}} style={{overflow:'hidden'}}>{faqs.slice(3).map(([question,answer]) => <FaqItem key={question} question={question} answer={answer}/>)}</motion.div>}</AnimatePresence><div className="hero-actions"><button className="button secondary" onClick={() => setExpanded(value => !value)}>{expanded ? 'Show Less' : 'Show More Questions'}</button></div></div></section>
}

function FaqItem({ question, answer, open = false }) { return <details open={open}><summary>{question}</summary><p>{answer}</p></details> }
function Feature({Icon,title,text}) { return <motion.div className="feature-card" whileHover={{y:-6}}><div className="feature-icon"><Icon size={21}/></div><h3>{title}</h3><p>{text}</p></motion.div> }
