import { useEffect, useMemo, useRef, useState } from 'react'
import { Info, KeyRound, Pencil, Share2, Sparkles, X } from 'lucide-react'
import { workspaceApi } from '../../services/api'
import { formatCurrency } from '../../utils/formatters'
import ConversationSidebar from './components/ConversationSidebar'
import ProviderSwitcher, { ProviderBadge } from './components/ProviderSwitcher'
import MessageList from './components/MessageList'
import Composer from './components/Composer'
import CommandWorkflow, { parseCommands } from './components/CommandWorkflow'
import './chat.css'
import './chat-functional.css'
import './chat-scroll-fix.css'
import './chat-images.css'

const prompts = ['Explain', 'Fix', 'Refactor', 'Tests', 'Review', 'Optimize', 'Generate docs']

function KeySetup({ onDone, onCancel }) { const [form, setForm] = useState({ label: '', provider: 'OpenAI', model: 'gpt-4o-mini', api_key: '', api_base_url: '' }); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const custom = form.provider === 'Custom'; const save = async e => { e.preventDefault(); setSaving(true); setError(''); try { await workspaceApi.personalKey({ ...form, label: form.label || undefined, api_base_url: form.api_base_url || undefined }); await onDone() } catch (err) { setError(err.response?.data?.detail || 'Could not save your API key.') } finally { setSaving(false) } }; return <div className="tp-modal-backdrop"><form className="tp-key-setup" onSubmit={save}><header><div><span>SECURE CONNECTION</span><h2>Add personal API key</h2></div>{onCancel && <button type="button" onClick={onCancel}><X size={17}/></button>}</header><p>Your key is encrypted before storage and never returned to this browser.</p><label>Friendly name<input value={form.label} onChange={e => setForm({ ...form, label: e.target.value })} placeholder={`${form.provider} Personal`}/></label><div className="tp-key-grid"><label>Provider<select value={form.provider} onChange={e => { const provider = e.target.value; setForm({ ...form, provider, model: provider === 'Gemini' ? 'gemini-2.5-flash' : provider === 'OpenAI' ? 'gpt-4o-mini' : form.model }) }}><option>OpenAI</option><option>Gemini</option><option>Claude</option><option>Groq</option><option>Custom</option></select></label><label>Model<input value={form.model} onChange={e => setForm({ ...form, model: e.target.value })} required/></label></div>{custom && <label>OpenAI-compatible endpoint<input type="url" value={form.api_base_url} onChange={e => setForm({ ...form, api_base_url: e.target.value })} required/></label>}<label>API key<input type="password" value={form.api_key} onChange={e => setForm({ ...form, api_key: e.target.value })} required/></label>{error && <small className="tp-form-error">{error}</small>}<footer>{onCancel && <button type="button" className="tp-secondary" onClick={onCancel}>Cancel</button>}<button className="tp-primary" disabled={saving}><KeyRound size={15}/>{saving ? 'Saving…' : 'Save securely'}</button></footer></form></div> }
function EmptyState({ onPrompt, inputRef }) { return <div className="tp-empty"><div className="tp-empty-icon"><Sparkles size={19}/></div><span>TOKENPILOT AI</span><h1>How can I help you today?</h1><div>{prompts.map(prompt => <button key={prompt} onClick={() => { onPrompt(prompt); inputRef.current?.focus() }}>{prompt}</button>)}</div></div> }
function KeyManager({ keys, onClose, onRefresh, onAdd }) { const rename = async key => { const label = window.prompt('Rename API key', key.label); if (label?.trim()) { await workspaceApi.updatePersonalKey(key.id, { label: label.trim() }); onRefresh() } }; return <div className="tp-modal-backdrop"><div className="tp-key-manager"><header><div><span>PERSONAL KEYS</span><h2>Manage connections</h2></div><button onClick={onClose}><X size={17}/></button></header><p>Company keys are managed by your organization and remain available in the switcher.</p>{keys.map(key => <section key={key.id}><ProviderBadge provider={key.provider}/><div><b>{key.label}</b><small>{key.provider} · {key.model} · Encrypted {key.is_default ? '· Default' : ''}</small></div><button onClick={() => workspaceApi.updatePersonalKey(key.id, { is_default: true }).then(onRefresh)}>Default</button><button onClick={() => rename(key)}>Rename</button><button className="danger" onClick={() => window.confirm(`Delete ${key.label}?`) && workspaceApi.deletePersonalKey(key.id).then(onRefresh)}>Delete</button></section>)}<button className="tp-primary full" onClick={onAdd}>Add personal API key</button></div></div> }

export default function ChatWorkspace({ embedded = false, initialPrompt = '', onAssistantResponse }) {
  const [connections, setConnections] = useState({ personal: [], organization: [] }); const [selected, setSelected] = useState(); const [chats, setChats] = useState([]); const [chat, setChat] = useState(); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all'); const [pinned, setPinned] = useState(() => new Set(JSON.parse(localStorage.getItem('tokenpilot_pinned_chats') || '[]'))); const [archived, setArchived] = useState(() => new Set(JSON.parse(localStorage.getItem('tokenpilot_archived_chats') || '[]'))); const [prompt, setPrompt] = useState(initialPrompt); const [images, setImages] = useState([]); const [loading, setLoading] = useState(false); const [keySetup, setKeySetup] = useState(false); const [keyManager, setKeyManager] = useState(false); const [info, setInfo] = useState(false); const [error, setError] = useState(''); const [workflow, setWorkflow] = useState({ commands: [], statuses: {}, logs: [] }); const bottomRef = useRef(); const inputRef = useRef()
  const allKeys = useMemo(() => [...connections.organization, ...connections.personal], [connections])
  useEffect(() => { if (selected) { localStorage.setItem('tokenpilot_selected_connection', JSON.stringify({ id: selected.id, source: selected.source })); return } try { const saved = JSON.parse(localStorage.getItem('tokenpilot_selected_connection') || 'null'); const match = allKeys.find(key => key.id === saved?.id && key.source === saved?.source); if (match) setSelected(match) } catch {} }, [allKeys, selected])
  const loadConnections = async () => { try { const r = await workspaceApi.connections(); const next = r.data || { personal: [], organization: [] }; setConnections(next); setSelected(current => [...next.organization, ...next.personal].find(key => key.id === current?.id && key.source === current?.source) || next.organization[0] || next.personal[0]) } catch { const r = await workspaceApi.personalKeys(); const personal = r.data || []; setConnections({ personal, organization: [] }); setSelected(current => personal.find(key => key.id === current?.id) || personal[0]) } }
  const loadChats = async value => { const r = await workspaceApi.chats(value); setChats(r.data || []) }
  const createChat = async () => { const r = await workspaceApi.createChat(); setChat({ ...r.data, messages: [] }); await loadChats(search); inputRef.current?.focus() }
  const openChat = async id => { const r = await workspaceApi.chat(id); setChat(r.data) }
  const renameChat = async item => { const title = window.prompt('Rename conversation', item.title); if (title?.trim()) { await workspaceApi.renameChat(item.id, { title: title.trim() }); await loadChats(search); if (chat?.id === item.id) setChat(current => ({ ...current, title: title.trim() })) } }
  const deleteChat = async id => { if (!window.confirm('Delete this conversation?')) return; await workspaceApi.deleteChat(id); if (chat?.id === id) setChat(undefined); await loadChats(search) }
  const toggleLocal = (setter, storageKey, id) => setter(current => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); localStorage.setItem(storageKey, JSON.stringify([...next])); return next })
  const addImages = async files => { const remaining = 4 - images.length; const valid = files.slice(0, remaining).filter(file => ['image/jpeg', 'image/png', 'image/webp', 'image/gif'].includes(file.type) && file.size <= 3 * 1024 * 1024); if (valid.length !== files.slice(0, remaining).length) setError('Images must be JPG, PNG, WebP, or GIF and no larger than 3 MB.'); const encoded = await Promise.all(valid.map(file => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve({ name: file.name, mime_type: file.type, data: String(reader.result).split(',')[1] }); reader.onerror = reject; reader.readAsDataURL(file) }))); setImages(current => [...current, ...encoded]) }
  const send = async forced => { const content = (forced ?? prompt).trim(); const outgoingImages = forced === undefined ? images : []; if ((!content && !outgoingImages.length) || loading) return; let target = chat; if (!target) { const r = await workspaceApi.createChat(); target = r.data; setChat({ ...target, messages: [] }) } if (!selected) { setKeySetup(true); return } setPrompt(''); setImages([]); setError(''); setLoading(true); setChat(current => ({ ...current, messages: [...(current?.messages || []), { role: 'user', content: content || '[Image attachment]', images: outgoingImages }] })); try { const r = await workspaceApi.send(target.id, { content, images: outgoingImages.map(({ mime_type, data }) => ({ mime_type, data })), key_id: selected.id, key_source: selected.source }); setChat(current => ({ ...current, title: current.title === 'New conversation' ? (content || 'Image attachment').slice(0, 60) : current.title, messages: [...current.messages, { ...r.data, provider: selected.label, model: selected.model }] })); onAssistantResponse?.({ prompt: content, content: r.data?.content || '' }); window.dispatchEvent(new CustomEvent('tokenpilot:assistant-response', { detail:{ prompt:content, content:r.data?.content || '' } })); await loadChats(search) } catch (err) { setError(typeof err.response?.data?.detail === 'string' ? err.response.data.detail : 'The selected provider could not complete this request.') } finally { setLoading(false) } }
  const importFile = file => { const reader = new FileReader(); reader.onload = () => setPrompt(current => `${current}${current ? '\n\n' : ''}Please analyze this file (${file.name}):\n\n\`\`\`\n${String(reader.result).slice(0, 30000)}\n\`\`\``); reader.readAsText(file) }
  const visibleChats = useMemo(() => chats.filter(item => !archived.has(item.id)).map(item => ({ ...item, pinned: pinned.has(item.id) })).filter(item => filter === 'all' || filter === 'recent' || item.pinned).sort((a, b) => Number(b.pinned) - Number(a.pinned)), [chats, archived, pinned, filter])
 useEffect(() => { Promise.all([loadConnections(), loadChats()]).catch(() => {}) }, []); useEffect(() => { const timer = setTimeout(() => loadChats(search).catch(() => {}), 250); return () => clearTimeout(timer) }, [search]); useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [chat?.messages?.length, loading]); useEffect(() => { const shortcut = event => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); createChat() } if (event.key === '/' && !['TEXTAREA', 'INPUT'].includes(document.activeElement?.tagName)) { event.preventDefault(); document.querySelector('.tp-search input')?.focus() } }; window.addEventListener('keydown', shortcut); return () => window.removeEventListener('keydown', shortcut) }, [chat, search])
  useEffect(() => { const handleAgentResponse = event => { const commands = parseCommands(event.detail?.content); if (commands.length) setWorkflow(current => ({ ...current, commands:[...current.commands, ...commands], statuses:{ ...current.statuses, ...Object.fromEntries(commands.map(command => [command.command, 'Pending'])) } })) }; window.addEventListener('tokenpilot:assistant-response', handleAgentResponse); return () => window.removeEventListener('tokenpilot:assistant-response', handleAgentResponse) }, [])
  useEffect(() => { Promise.all([loadConnections(), loadChats()]).catch(() => {}) }, []); useEffect(() => { const timer = setTimeout(() => loadChats(search).catch(() => {}), 250); return () => clearTimeout(timer) }, [search]); useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [chat?.messages?.length, loading]); useEffect(() => { const shortcut = event => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); createChat() } if (event.key === '/' && !['TEXTAREA', 'INPUT'].includes(document.activeElement?.tagName)) { event.preventDefault(); document.querySelector('.tp-search input')?.focus() } }; window.addEventListener('keydown', shortcut); return () => window.removeEventListener('keydown', shortcut) }, [chat, search])
  if (keySetup) return <KeySetup onDone={async () => { setKeySetup(false); await loadConnections() }} onCancel={allKeys.length ? () => setKeySetup(false) : null}/>
  if (keyManager) return <KeyManager keys={connections.personal} onClose={() => setKeyManager(false)} onRefresh={async () => { await loadConnections(); setKeyManager(false) }} onAdd={() => { setKeyManager(false); setKeySetup(true) }}/>
 return <div className={`tp-chat-app ${embedded ? 'embedded' : ''}`}><ConversationSidebar chats={visibleChats} activeId={chat?.id} search={search} onSearch={setSearch} onNew={createChat} onOpen={openChat} onRename={renameChat} onDelete={deleteChat} onPin={id => toggleLocal(setPinned, 'tokenpilot_pinned_chats', id)} onArchive={id => toggleLocal(setArchived, 'tokenpilot_archived_chats', id)} filter={filter} onFilter={setFilter} provider={selected?.provider}/><main className="tp-chat-main"><header className="tp-chat-header"><div><b>{chat?.title || 'New chat'}</b>{chat && <button onClick={() => renameChat(chat)}><Pencil size={13}/></button>}</div><section><ProviderSwitcher selected={selected} companyKeys={connections.organization} personalKeys={connections.personal} onSelect={setSelected} onAdd={() => setKeySetup(true)} onManage={() => setKeyManager(true)}/><button title="Share conversation link" onClick={() => { navigator.clipboard?.writeText(window.location.href); setError('Conversation link copied to clipboard.') }}><Share2 size={16}/></button><button title="Conversation info" onClick={() => setInfo(!info)}><Info size={16}/></button></section></header>{info && <aside className="tp-info-popover"><button onClick={() => setInfo(false)}><X size={14}/></button><ProviderBadge provider={selected?.provider}/><b>{selected?.label}</b><small>{selected?.model}</small><hr/><span>Tokens <b>{((chat?.messages?.length || 0) * 128).toLocaleString()}</b></span><span>Estimated cost <b>{formatCurrency((chat?.messages?.length || 0) * .0001)}</b></span><span>Context window <b>128k</b></span></aside>}<div className="tp-chat-body">{!chat?.messages?.length ? <EmptyState onPrompt={setPrompt} inputRef={inputRef}/> : <MessageList messages={chat.messages} loading={loading} onEdit={setPrompt} onRegenerate={send} bottomRef={bottomRef}/>} {error && <div className="tp-chat-error">{error}<button onClick={() => setError('')}><X size={14}/></button></div>}</div><Composer value={prompt} images={images} onChange={setPrompt} onImages={addImages} onRemoveImage={index => setImages(current => current.filter((_, itemIndex) => itemIndex !== index))} onSend={send} loading={loading} inputRef={inputRef} onTextFile={importFile}/></main></div>
  return <div className={`tp-chat-app ${embedded ? 'embedded' : ''}`}><ConversationSidebar chats={visibleChats} activeId={chat?.id} search={search} onSearch={setSearch} onNew={createChat} onOpen={openChat} onRename={renameChat} onDelete={deleteChat} onPin={id => toggleLocal(setPinned, 'tokenpilot_pinned_chats', id)} onArchive={id => toggleLocal(setArchived, 'tokenpilot_archived_chats', id)} filter={filter} onFilter={setFilter} provider={selected?.provider}/><main className="tp-chat-main"><header className="tp-chat-header"><div><b>{chat?.title || 'New chat'}</b>{chat && <button onClick={() => renameChat(chat)}><Pencil size={13}/></button>}</div><section><ProviderSwitcher selected={selected} companyKeys={connections.organization} personalKeys={connections.personal} onSelect={setSelected} onAdd={() => setKeySetup(true)} onManage={() => setKeyManager(true)}/><button title="Share conversation link" onClick={() => { navigator.clipboard?.writeText(window.location.href); setError('Conversation link copied to clipboard.') }}><Share2 size={16}/></button><button title="Conversation info" onClick={() => setInfo(!info)}><Info size={16}/></button></section></header>{info && <aside className="tp-info-popover"><button onClick={() => setInfo(false)}><X size={14}/></button><ProviderBadge provider={selected?.provider}/><b>{selected?.label}</b><small>{selected?.model}</small><hr/><span>Tokens <b>{((chat?.messages?.length || 0) * 128).toLocaleString()}</b></span><span>Estimated cost <b>{formatCurrency((chat?.messages?.length || 0) * .0001)}</b></span><span>Context window <b>128k</b></span></aside>}<div className="tp-chat-body">{!chat?.messages?.length ? <EmptyState onPrompt={setPrompt} inputRef={inputRef}/> : <MessageList messages={chat.messages} loading={loading} onEdit={setPrompt} onRegenerate={send} bottomRef={bottomRef} commandStatuses={workflow.statuses} onCommandStatus={(command, status) => setWorkflow(current => ({ ...current, statuses:{ ...current.statuses, [command]:status } }))}/>} {error && <div className="tp-chat-error">{error}<button onClick={() => setError('')}><X size={14}/></button></div>}</div><Composer value={prompt} images={images} onChange={setPrompt} onImages={addImages} onRemoveImage={index => setImages(current => current.filter((_, itemIndex) => itemIndex !== index))} onSend={send} loading={loading} inputRef={inputRef} onTextFile={importFile}/></main></div>
}
