import { useRef } from 'react'
import { Code2, FileUp, ImagePlus, Paperclip, Send, X } from 'lucide-react'

export default function Composer({ value, images = [], documents = (typeof window !== 'undefined' ? window.tokenpilotDocuments || [] : []), onChange, onImages, onRemoveImage, onSend, loading, inputRef, onTextFile }) {
  const fileInput = useRef()
  const imageInput = useRef()
  const selectFile = () => fileInput.current?.click()
  const selectImage = () => imageInput.current?.click()
  const readFile = event => { const file = event.target.files?.[0]; event.target.value = ''; if (file) onTextFile(file) }
  const readImages = event => { const files = [...(event.target.files || [])]; event.target.value = ''; if (files.length) onImages(files) }
  const canSend = (value.trim() || images.length || documents.length) && !loading
  return <div className="tp-composer-wrap"><input ref={fileInput} className="tp-hidden-input" type="file" accept=".pdf,.docx,.txt,.md,.js,.jsx,.ts,.tsx,.py,.json,.html,.css,.sql" onChange={readFile}/><input ref={imageInput} className="tp-hidden-input" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple onChange={readImages}/><div className="tp-composer-tools"><button title="Attach a document or text file" onClick={selectFile}><Paperclip size={16}/></button><button title="Attach image" onClick={selectImage}><ImagePlus size={16}/></button><button title="Upload a document or text file" onClick={selectFile}><FileUp size={16}/></button><button title="Insert code block" onClick={() => onChange(`${value}${value ? '\n\n' : ''}\`\`\`\n\n\`\`\``)}><Code2 size={16}/></button><span>Shift + Enter for a new line</span></div><div className="tp-composer">{images.length > 0 && <div className="tp-image-previews">{images.map((image, index) => <figure key={`${image.name}-${index}`}><img src={`data:${image.mime_type};base64,${image.data}`} alt={image.name}/><button title={`Remove ${image.name}`} onClick={() => onRemoveImage(index)}><X size={12}/></button></figure>)}</div>}{documents.length > 0 && <div className="tp-file-attachment">{documents.map(document => <span key={document.name}>📎 {document.name}</span>)}</div>}<textarea ref={inputRef} value={value} onChange={e => onChange(e.target.value)} maxLength={50000} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); onSend() } }} placeholder="Message TokenPilot AI…"/><footer><span>{value.length.toLocaleString()} / 50,000 · ~{Math.ceil(value.length / 4)} tokens</span><button disabled={!canSend} onClick={() => onSend()}><Send size={16}/></button></footer></div></div>
}
