import { useState } from 'react'
import { Bot, Check, Copy, Pencil, RefreshCw, ThumbsDown, ThumbsUp } from 'lucide-react'
import { CommandCard, parseCommands } from './CommandWorkflow'

function Markdown({ value }) { const parts = String(value || '').split(/```([\s\S]*?)```/g); return <div className="tp-markdown">{parts.map((part, index) => index % 2 ? <pre key={index}><code>{part.replace(/^\w+\n/, '')}</code><button onClick={() => navigator.clipboard?.writeText(part)}><Copy size={13}/></button></pre> : part.split('\n').map((line, i) => <p key={`${index}-${i}`}>{line || ' '}</p>))}</div> }

export default function MessageList({ messages, loading, onEdit, onRegenerate, bottomRef, commandStatuses = {}, onCommandStatus }) {
  const [copied, setCopied] = useState(null)
  const [reactions, setReactions] = useState({})
  const copyMessage = async (message, id) => { try { await navigator.clipboard?.writeText(message); setCopied(id); window.setTimeout(() => setCopied(current => current === id ? null : current), 1500) } catch { setCopied(null) } }
  const react = (id, value) => setReactions(current => ({ ...current, [id]: current[id] === value ? null : value }))
  return <div className="tp-message-list">{messages.map((message, index) => { const id = message.id || index; const reaction = reactions[id]; const prompt = messages[index - 1]?.content || ''; const commands = message.role === 'assistant' ? parseCommands(message.content) : []; return <article className={`tp-message ${message.role}`} key={id}><div className="tp-avatar">{message.role === 'assistant' ? <Bot size={16}/> : 'You'}</div><div className="tp-message-content"><div className="tp-message-heading"><b>{message.role === 'assistant' ? message.provider || 'TokenPilot AI' : 'You'}</b><small>{message.model || (message.created_at ? new Date(message.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : 'Now')}</small></div>{message.images?.length > 0 && <div className="tp-message-images">{message.images.map((image, imageIndex) => <img key={imageIndex} src={`data:${image.mime_type};base64,${image.data}`} alt="Uploaded attachment"/>)}</div>}<Markdown value={message.content}/>{commands.map((command, commandIndex) => <CommandCard key={`${id}-command-${commandIndex}`} item={command} status={commandStatuses[command.command] || 'Pending'} onCopy={() => navigator.clipboard?.writeText(command.command)} onStatus={status => onCommandStatus?.(command.command, status)}/>)}{message.role === 'assistant' && <div className="tp-message-actions"><button onClick={() => copyMessage(message.content, id)}>{copied === id ? <Check size={13}/> : <Copy size={13}/>} {copied === id ? 'Copied' : 'Copy'}</button><button onClick={() => onEdit(prompt)} disabled={!prompt}><Pencil size={13}/> Edit prompt</button><button onClick={() => onRegenerate(prompt)} disabled={!prompt || loading}><RefreshCw size={13}/> Regenerate</button><button className={reaction === 'up' ? 'selected' : ''} onClick={() => react(id, 'up')} aria-label="Like response"><ThumbsUp size={13}/></button><button className={reaction === 'down' ? 'selected' : ''} onClick={() => react(id, 'down')} aria-label="Dislike response"><ThumbsDown size={13}/></button></div>}</div></article> })}{loading && <article className="tp-message assistant"><div className="tp-avatar"><Bot size={16}/></div><div className="tp-thinking"><i/><i/><i/><span>Thinking</span></div></article>}<div ref={bottomRef}/></div>
}
